name: tanks_script

env:
  BLENDER_VERSION: 2.93lts/stable

on:
  push:
    paths:
      - tanks_script/**
      - .github/workflows/tanks_script.yml

jobs:
  html5:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        uses: armory3d/armory_gh_actions@v0.1.13
        with:
          publish: html5
          blend: ${{ github.workflow }}/${{ github.workflow }}.blend
          blender: ${{ env.BLENDER_VERSION }}
      - name: Deploy gh-pages
        uses: JamesIves/github-pages-deploy-action@v4.3.0
        with:
          branch: gh-pages
          folder: ${{ github.workflow }}/build_${{ github.workflow }}/html5
          target-folder: ${{ github.workflow }}
  krom-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        uses: armory3d/armory_gh_actions@v0.1.13
        with:
          publish: krom-linux
          blend: ${{ github.workflow }}/${{ github.workflow }}.blend
          blender: ${{ env.BLENDER_VERSION }}
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        uses: armory3d/armory_gh_actions@v0.1.13
        with:
          publish: linux-hl
          blend: ${{ github.workflow }}/${{ github.workflow }}.blend
          blender: ${{ env.BLENDER_VERSION }}
  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        uses: armory3d/armory_gh_actions@v0.1.13
        with:
          publish: android-hl
          blend: ${{ github.workflow }}/${{ github.workflow }}.blend
          blender: ${{ env.BLENDER_VERSION }}
  windows:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        uses: armory3d/armory_gh_actions@v0.1.13
        with:
          publish: windows-hl
          blend: ${{ github.workflow }}/${{ github.workflow }}.blend
          blender: ${{ env.BLENDER_VERSION }}
  macos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        uses: armory3d/armory_gh_actions@v0.1.13
        with:
          publish: macos-hl
          blend: ${{ github.workflow }}/${{ github.workflow }}.blend
          blender: ${{ env.BLENDER_VERSION }}
  ios:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        uses: armory3d/armory_gh_actions@v0.1.13
        with:
          publish: ios-hl
          blend: ${{ github.workflow }}/${{ github.workflow }}.blend
          blender: ${{ env.BLENDER_VERSION }}
